//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cache
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int Id { get; set; }
        public string Ean { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> InStock { get; set; }
        public Nullable<System.DateTime> ExpectedRestock { get; set; }
    }
}
