//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cache
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public string productdescription { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string categoryname { get; set; }
        public Nullable<int> brandid { get; set; }
        public Nullable<decimal> minprice { get; set; }
        public Nullable<decimal> maxprice { get; set; }
    }
}
