//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cache
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrappings
    {
        public int id { get; set; }
        public Nullable<int> typeid { get; set; }
        public string typename { get; set; }
        public Nullable<int> rangeid { get; set; }
        public string rangename { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> size { get; set; }
    }
}
